const main= '<?xml version="1.0" encoding="utf-8"?>'+
	'<kml xmlns="http://earth.google.com/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2">'+
	'<Document>'+
    '<Snippet>Sea Tel</Snippet>';
   
 const style_text ='   <Style id="track-none_n">'+
 '     <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-none_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="empty">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-none_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-none_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-0_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-0.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-0_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-0.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-0">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-0_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-0_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'<StyleMap id="track-16">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-0_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-0_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-1_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-1.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-1_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-1.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-1">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-1_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-1_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-2_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-2.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-2_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-2.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-2">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-2_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-2_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-3_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-3.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-3_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-3.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-3">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-3_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-3_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-4_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-4.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-4_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-4.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-4">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-4_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-4_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-5_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-5.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-5_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-5.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-5">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-5_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-5_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-6_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-6.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-6_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-6.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-6">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-6_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-6_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-7_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-7.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-7_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-7.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-7">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-7_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-7_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-8_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-8.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-8_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-8.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-8">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-8_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-8_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-9_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-9.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-9_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-9.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-9">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-9_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-9_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-10_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-10.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-10_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-10.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-10">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-10_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-10_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-11_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-11.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-11_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-11.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-11">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-11_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-11_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-12_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-12.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-12_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-12.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-12">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-12_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-12_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-13_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-13.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-13_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-13.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-13">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-13_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-13_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-14_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-14.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-14_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-14.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-14">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-14_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-14_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="track-15_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-15.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="track-15_h">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-15.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="track-15">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#track-15_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#track-15_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="warning_n">'+
'      <IconStyle>'+
'        <color>ff3399ff</color>'+
'        <scale>0.8</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="warning_h">'+
'      <IconStyle>'+
'        <color>ff3399ff</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="warning">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#warning_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#warning_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="error_n">'+
'      <IconStyle>'+
'        <color>a0ff00ff</color>'+
'        <scale>0.8</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="error_h">'+
'      <IconStyle>'+
'        <color>a0ff00ff</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="error">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#error_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#error_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="blockingWarning_n">'+
'      <IconStyle>'+
'        <color>c00000ff</color>'+
'        <scale>0.8</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://maps.google.com/mapfiles/kml/paddle/B-lv.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="blockingWarning_h">'+
'      <IconStyle>'+
'        <color>c00000ff</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://maps.google.com/mapfiles/kml/paddle/B-lv.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="blockingWarning">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#blockingWarning_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#blockingWarning_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="blockingError_n">'+
'      <IconStyle>'+
'        <color>a0ff00ff</color>'+
'        <scale>0.8</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://maps.google.com/mapfiles/kml/paddle/B-lv.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'      <LabelStyle>'+
'        <scale>0</scale>'+
'      </LabelStyle>'+
'    </Style>'+
'    <Style id="blockingError_h">'+
'      <IconStyle>'+
'        <color>a0ff00ff</color>'+
'        <scale>1.2</scale>'+
'        <heading>0</heading>'+
'        <Icon>'+
'          <href>http://maps.google.com/mapfiles/kml/paddle/B-lv.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="blockingError">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#blockingError_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#blockingError_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>'+
'    <Style id="trackLine-Single">'+
'      <LineStyle>'+
'        <color>ff00ff7f</color>'+
'        <width>2</width>'+
'      </LineStyle>'+
'    </Style>'+
'<Style id="trackLine-Single_block">'+
'      <LineStyle>'+
'        <color>ff0000ff</color>'+
'        <width>2</width>'+
'      </LineStyle>'+
'    </Style>'+
'<Style id="trackLine-Single_warning">'+
'      <LineStyle>'+
'        <color>ff00a5ff</color>'+
'        <width>2</width>'+
'      </LineStyle>'+
'    </Style>'+
'    <Style id="waypoint_n">'+
'      <IconStyle>'+
'        <color>ff00ff7f</color>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <Style id="waypoint_h">'+
'      <IconStyle>'+
'        <color>a0ff00ff</color>'+
'        <scale>1.2</scale>'+
'        <Icon>'+
'          <href>http://earth.google.com/images/kml-icons/track-directional/track-none.png</href>'+
'        </Icon>'+
'      </IconStyle>'+
'    </Style>'+
'    <StyleMap id="waypoint">'+
'      <Pair>'+
'        <key>normal</key>'+
'        <styleUrl>#waypoint_n</styleUrl>'+
'      </Pair>'+
'      <Pair>'+
'        <key>highlight</key>'+
'        <styleUrl>#waypoint_h</styleUrl>'+
'      </Pair>'+
'    </StyleMap>';
   